import { PrismaClient, OrgCategory, ActionType, RippleStatus } from '@prisma/client';

const prisma = new PrismaClient({
  datasources: { db: { url: process.env.DATABASE_URL } },
});

async function main() {
  console.log('Seeding database...');

  // Organizations
  const orgs = await Promise.all([
    prisma.organization.upsert({
      where: { slug: 'doctors-without-borders' },
      update: {},
      create: {
        name: 'Doctors Without Borders',
        slug: 'doctors-without-borders',
        ein: '13-3433391',
        mission: 'We provide medical care to people affected by conflict, epidemics, disasters, or exclusion from healthcare.',
        description: 'Médecins Sans Frontières (MSF) is an international humanitarian organization that provides medical assistance to people affected by conflict, epidemics, disasters, or exclusion from healthcare. MSF works in over 70 countries worldwide.',
        category: OrgCategory.HEALTH,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 84.6,
        donateUrl: 'https://www.doctorswithoutborders.org/donate',
        volunteerUrl: 'https://www.doctorswithoutborders.org/work-us',
        websiteUrl: 'https://www.doctorswithoutborders.org',
        imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=1200&h=400&fit=crop',
        totalRaised: 2400000,
        totalDonors: 8200,
        totalVolunteers: 340,
        weeklyDonations: 18400,
        weeklyDonors: 63,
        trending: true,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'world-wildlife-fund' },
      update: {},
      create: {
        name: 'World Wildlife Fund',
        slug: 'world-wildlife-fund',
        ein: '52-1693387',
        mission: 'To conserve nature and reduce the most pressing threats to the diversity of life on Earth.',
        description: 'WWF works to help local communities conserve the natural resources they depend upon, transform markets and policies toward sustainability, and protect and restore species and their habitats.',
        category: OrgCategory.ENVIRONMENT,
        charityNavigatorRating: 3.0,
        starRating: 3,
        percentToPrograms: 80.1,
        donateUrl: 'https://www.worldwildlife.org/donate',
        volunteerUrl: 'https://www.worldwildlife.org/about/volunteer',
        websiteUrl: 'https://www.worldwildlife.org',
        imageUrl: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=400&fit=crop',
        totalRaised: 1800000,
        totalDonors: 6100,
        totalVolunteers: 210,
        weeklyDonations: 14200,
        weeklyDonors: 48,
        trending: true,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'khan-academy' },
      update: {},
      create: {
        name: 'Khan Academy',
        slug: 'khan-academy',
        ein: '26-1544963',
        mission: 'To provide a free, world-class education for anyone, anywhere.',
        description: 'Khan Academy offers practice exercises, instructional videos, and a personalized learning dashboard that empower learners to study at their own pace in and outside of the classroom.',
        category: OrgCategory.EDUCATION,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 86.3,
        donateUrl: 'https://www.khanacademy.org/donate',
        websiteUrl: 'https://www.khanacademy.org',
        imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&h=400&fit=crop',
        totalRaised: 950000,
        totalDonors: 4200,
        totalVolunteers: 120,
        weeklyDonations: 8600,
        weeklyDonors: 37,
        trending: false,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'feeding-america' },
      update: {},
      create: {
        name: 'Feeding America',
        slug: 'feeding-america',
        ein: '36-3673599',
        mission: 'To advance change in America by ensuring equitable access to nutritious food for all in need.',
        description: 'Feeding America is the largest hunger-relief organization in the United States. Through a network of 200 food banks and 60,000 food pantries and meal programs, we help more than 40 million people facing hunger every year.',
        category: OrgCategory.POVERTY,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 98.7,
        donateUrl: 'https://www.feedingamerica.org/donate',
        volunteerUrl: 'https://www.feedingamerica.org/take-action/volunteer',
        websiteUrl: 'https://www.feedingamerica.org',
        imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=400&fit=crop',
        totalRaised: 3200000,
        totalDonors: 11400,
        totalVolunteers: 890,
        weeklyDonations: 24600,
        weeklyDonors: 88,
        trending: true,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'aspca' },
      update: {},
      create: {
        name: 'ASPCA',
        slug: 'aspca',
        ein: '13-1623829',
        mission: 'To provide effective means for the prevention of cruelty to animals throughout the United States.',
        description: 'The American Society for the Prevention of Cruelty to Animals (ASPCA) was the first humane organization in the Western Hemisphere. Our mission, as stated by founder Henry Bergh in 1866, is "to provide effective means for the prevention of cruelty to animals throughout the United States."',
        category: OrgCategory.ANIMALS,
        charityNavigatorRating: 3.0,
        starRating: 3,
        percentToPrograms: 75.4,
        donateUrl: 'https://www.aspca.org/donate',
        volunteerUrl: 'https://www.aspca.org/take-action/volunteer',
        websiteUrl: 'https://www.aspca.org',
        imageUrl: 'https://images.unsplash.com/photo-1601758003122-53c40e686a19?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1601758003122-53c40e686a19?w=1200&h=400&fit=crop',
        totalRaised: 1100000,
        totalDonors: 5600,
        totalVolunteers: 430,
        weeklyDonations: 9800,
        weeklyDonors: 41,
        trending: false,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'american-red-cross' },
      update: {},
      create: {
        name: 'American Red Cross',
        slug: 'american-red-cross',
        ein: '53-0196605',
        mission: 'To prevent and alleviate human suffering in the face of emergencies by mobilizing the power of volunteers and the generosity of donors.',
        description: 'The American Red Cross prevents and alleviates human suffering in the face of emergencies by mobilizing the power of volunteers and the generosity of donors. We are a volunteer-led humanitarian organization that provides emergency assistance, disaster relief, and disaster preparedness education in the United States.',
        category: OrgCategory.DISASTER_RELIEF,
        charityNavigatorRating: 3.0,
        starRating: 3,
        percentToPrograms: 91.0,
        donateUrl: 'https://www.redcross.org/donate',
        volunteerUrl: 'https://www.redcross.org/volunteer',
        websiteUrl: 'https://www.redcross.org',
        imageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1200&h=400&fit=crop',
        totalRaised: 4100000,
        totalDonors: 14200,
        totalVolunteers: 1200,
        weeklyDonations: 31400,
        weeklyDonors: 112,
        trending: true,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'habitat-for-humanity' },
      update: {},
      create: {
        name: 'Habitat for Humanity',
        slug: 'habitat-for-humanity',
        ein: '91-1914868',
        mission: 'Seeking to put God\'s love into action, Habitat for Humanity brings people together to build homes, communities and hope.',
        description: 'Habitat for Humanity is a global nonprofit housing organization working in local communities across all 50 states in the U.S. and in approximately 70 countries. Habitat\'s vision is of a world where everyone has a decent place to live.',
        category: OrgCategory.COMMUNITY,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 69.1,
        donateUrl: 'https://www.habitat.org/donate',
        volunteerUrl: 'https://www.habitat.org/volunteer',
        websiteUrl: 'https://www.habitat.org',
        imageUrl: 'https://images.unsplash.com/photo-1582560475093-ba66accbc095?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1582560475093-ba66accbc095?w=1200&h=400&fit=crop',
        totalRaised: 2800000,
        totalDonors: 9600,
        totalVolunteers: 2100,
        weeklyDonations: 21800,
        weeklyDonors: 74,
        trending: false,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'sierra-club-foundation' },
      update: {},
      create: {
        name: 'Sierra Club Foundation',
        slug: 'sierra-club-foundation',
        ein: '94-6069890',
        mission: 'To advance the preservation and protection of the natural environment by empowering the citizenry.',
        description: 'The Sierra Club Foundation supports critical environmental education, litigation, and advocacy work to protect communities and wild places throughout North America and beyond.',
        category: OrgCategory.ENVIRONMENT,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 88.2,
        donateUrl: 'https://www.sierraclubfoundation.org/donate',
        volunteerUrl: 'https://www.sierraclub.org/volunteer',
        websiteUrl: 'https://www.sierraclubfoundation.org',
        imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=400&fit=crop',
        totalRaised: 680000,
        totalDonors: 2800,
        totalVolunteers: 560,
        weeklyDonations: 6200,
        weeklyDonors: 26,
        trending: false,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'st-jude-childrens-hospital' },
      update: {},
      create: {
        name: "St. Jude Children's Research Hospital",
        slug: 'st-jude-childrens-hospital',
        ein: '62-0646012',
        mission: "Finding cures. Saving children. St. Jude is leading the way the world understands, treats and defeats childhood cancer and other life-threatening diseases.",
        description: "St. Jude Children's Research Hospital is a leading children's cancer center whose mission is to advance cures, and means of prevention, for pediatric catastrophic diseases through research and treatment.",
        category: OrgCategory.HEALTH,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 82.9,
        donateUrl: 'https://www.stjude.org/donate',
        volunteerUrl: 'https://www.stjude.org/get-involved/volunteer.html',
        websiteUrl: 'https://www.stjude.org',
        imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&h=400&fit=crop',
        totalRaised: 5800000,
        totalDonors: 19400,
        totalVolunteers: 680,
        weeklyDonations: 44200,
        weeklyDonors: 148,
        trending: true,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'room-to-read' },
      update: {},
      create: {
        name: 'Room to Read',
        slug: 'room-to-read',
        ein: '01-0618840',
        mission: 'World change starts with educated children.',
        description: 'Room to Read focuses on literacy and gender equality in education. We work in collaboration with local communities, partner organizations, and governments to develop literacy skills and a habit of reading among primary school children.',
        category: OrgCategory.EDUCATION,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 84.7,
        donateUrl: 'https://www.roomtoread.org/donate',
        websiteUrl: 'https://www.roomtoread.org',
        imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&h=400&fit=crop',
        totalRaised: 420000,
        totalDonors: 1800,
        totalVolunteers: 90,
        weeklyDonations: 3800,
        weeklyDonors: 16,
        trending: false,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'direct-relief' },
      update: {},
      create: {
        name: 'Direct Relief',
        slug: 'direct-relief',
        ein: '95-1831116',
        mission: 'To improve the health and lives of people affected by poverty or emergency situations by mobilizing and providing essential medical resources needed for their care.',
        description: 'Direct Relief is a humanitarian aid organization, active in all 50 states and more than 80 countries, with a mission to improve the health and lives of people affected by poverty or emergencies.',
        category: OrgCategory.DISASTER_RELIEF,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 99.0,
        donateUrl: 'https://www.directrelief.org/donate',
        websiteUrl: 'https://www.directrelief.org',
        imageUrl: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1200&h=400&fit=crop',
        totalRaised: 3600000,
        totalDonors: 12400,
        totalVolunteers: 280,
        weeklyDonations: 27800,
        weeklyDonors: 94,
        trending: false,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'humane-society' },
      update: {},
      create: {
        name: 'The Humane Society of the United States',
        slug: 'humane-society',
        ein: '53-0225390',
        mission: 'Celebrating animals, confronting cruelty.',
        description: 'The Humane Society of the United States is the most effective animal protection organization, as rated by peers and experts. We fight for all animals across many fronts.',
        category: OrgCategory.ANIMALS,
        charityNavigatorRating: 3.0,
        starRating: 3,
        percentToPrograms: 78.4,
        donateUrl: 'https://www.humanesociety.org/donate',
        volunteerUrl: 'https://www.humanesociety.org/get-involved',
        websiteUrl: 'https://www.humanesociety.org',
        imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=1200&h=400&fit=crop',
        totalRaised: 920000,
        totalDonors: 4100,
        totalVolunteers: 380,
        weeklyDonations: 8200,
        weeklyDonors: 34,
        trending: false,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'boys-girls-clubs' },
      update: {},
      create: {
        name: 'Boys & Girls Clubs of America',
        slug: 'boys-girls-clubs',
        ein: '13-5562976',
        mission: 'To enable all young people, especially those who need us most, to reach their full potential as productive, caring, responsible citizens.',
        description: 'Boys & Girls Clubs of America provide a safe place to learn and grow, ongoing relationships with caring, adult professionals, life-enhancing programs and character development experiences.',
        category: OrgCategory.COMMUNITY,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 77.9,
        donateUrl: 'https://www.bgca.org/donate',
        volunteerUrl: 'https://www.bgca.org/get-involved/volunteer',
        websiteUrl: 'https://www.bgca.org',
        imageUrl: 'https://images.unsplash.com/photo-1587652990758-ada1a5e9ece3?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&h=400&fit=crop',
        totalRaised: 1560000,
        totalDonors: 6800,
        totalVolunteers: 740,
        weeklyDonations: 13200,
        weeklyDonors: 56,
        trending: true,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'global-fund-for-women' },
      update: {},
      create: {
        name: 'Global Fund for Women',
        slug: 'global-fund-for-women',
        ein: '94-3138808',
        mission: 'Building a world where no one is left behind — a world where every woman and girl is powerful, safe, and represented.',
        description: "Global Fund for Women is one of the world's leading foundations for gender equality, standing for the full and equal rights of all women and girls. We fund, strengthen, and link women-led organizations and movements.",
        category: OrgCategory.POVERTY,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 81.5,
        donateUrl: 'https://www.globalfundforwomen.org/donate',
        websiteUrl: 'https://www.globalfundforwomen.org',
        imageUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1200&h=400&fit=crop',
        totalRaised: 740000,
        totalDonors: 3200,
        totalVolunteers: 150,
        weeklyDonations: 6800,
        weeklyDonors: 28,
        trending: false,
      },
    }),
    prisma.organization.upsert({
      where: { slug: 'ocean-conservancy' },
      update: {},
      create: {
        name: 'Ocean Conservancy',
        slug: 'ocean-conservancy',
        ein: '23-7245152',
        mission: 'Protecting the ocean from today\'s greatest global challenges.',
        description: 'Ocean Conservancy is working to protect the ocean from today\'s greatest global challenges. Together with our partners, we create science-based solutions for a healthy ocean and the wildlife and communities that depend on it.',
        category: OrgCategory.ENVIRONMENT,
        charityNavigatorRating: 4.0,
        starRating: 4,
        percentToPrograms: 83.4,
        donateUrl: 'https://www.oceanconservancy.org/donate',
        volunteerUrl: 'https://www.oceanconservancy.org/trash-free-seas/international-coastal-cleanup/volunteer',
        websiteUrl: 'https://www.oceanconservancy.org',
        imageUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=200&h=200&fit=crop',
        coverImageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1200&h=400&fit=crop',
        totalRaised: 580000,
        totalDonors: 2400,
        totalVolunteers: 890,
        weeklyDonations: 5200,
        weeklyDonors: 22,
        trending: true,
      },
    }),
  ]);

  console.log(`Created ${orgs.length} organizations`);

  // Demo users
  const users = await Promise.all([
    prisma.user.upsert({
      where: { googleId: 'demo-user-1' },
      update: {},
      create: {
        googleId: 'demo-user-1',
        name: 'Sarah Chen',
        avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=faces',
        bio: 'Making small waves every day 🌊 | Climate advocate | Dog mom',
        streak: 14,
        longestStreak: 28,
        totalGiven: 340,
        totalActions: 22,
      },
    }),
    prisma.user.upsert({
      where: { googleId: 'demo-user-2' },
      update: {},
      create: {
        googleId: 'demo-user-2',
        name: 'Marcus Williams',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces',
        bio: 'Habitat volunteer. Give what you can.',
        streak: 7,
        longestStreak: 21,
        totalGiven: 175,
        totalActions: 15,
      },
    }),
    prisma.user.upsert({
      where: { googleId: 'demo-user-3' },
      update: {},
      create: {
        googleId: 'demo-user-3',
        name: 'Priya Patel',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=faces',
        bio: 'Education is everything | Room to Read donor | Teacher',
        streak: 3,
        longestStreak: 14,
        totalGiven: 220,
        totalActions: 18,
      },
    }),
  ]);

  console.log(`Created ${users.length} demo users`);

  const [sarah, marcus, priya] = users;
  const [msf, wwf, khan, feeding, aspca, redcross, habitat] = orgs;

  // Active ripples
  const ripples = await Promise.all([
    prisma.ripple.upsert({
      where: { id: 'ripple-1' },
      update: {},
      create: {
        id: 'ripple-1',
        startedByUserId: sarah.id,
        orgId: msf.id,
        title: "Sarah's Emergency Relief Fund",
        description: "Help me hit $500 for Doctors Without Borders this week. Every dollar goes directly to the field.",
        targetAmount: 500,
        currentAmount: 340,
        participantCount: 14,
        status: RippleStatus.ACTIVE,
        expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.ripple.upsert({
      where: { id: 'ripple-2' },
      update: {},
      create: {
        id: 'ripple-2',
        startedByUserId: marcus.id,
        orgId: habitat.id,
        title: "Build Day Weekend",
        description: "Join me volunteering at Habitat's build day this weekend! Let's get 10 people together.",
        targetAmount: null,
        currentAmount: 0,
        participantCount: 6,
        status: RippleStatus.ACTIVE,
        expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
      },
    }),
  ]);

  console.log(`Created ${ripples.length} ripples`);

  // Actions
  const actions = await Promise.all([
    prisma.action.create({
      data: {
        userId: sarah.id,
        orgId: msf.id,
        type: ActionType.DONATE,
        amount: 50,
        comment: "For everyone in the field right now. You inspire me daily.",
        isPublic: true,
        rippleId: ripples[0].id,
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: marcus.id,
        orgId: habitat.id,
        type: ActionType.VOLUNTEER,
        comment: "Spent the morning building a home for a family in need. Best Saturday ever.",
        isPublic: true,
        rippleId: ripples[1].id,
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: priya.id,
        orgId: khan.id,
        type: ActionType.DONATE,
        amount: 25,
        comment: "Free education changed my life. Paying it forward.",
        isPublic: true,
        createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: sarah.id,
        orgId: wwf.id,
        type: ActionType.DONATE,
        amount: 30,
        isPublic: true,
        createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: marcus.id,
        orgId: feeding.id,
        type: ActionType.DONATE,
        amount: 75,
        comment: "No one should go hungry. Period.",
        isPublic: true,
        createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: priya.id,
        orgId: msf.id,
        type: ActionType.DONATE,
        amount: 100,
        comment: "Matching Sarah's ripple. Let's get to $500!",
        isPublic: true,
        rippleId: ripples[0].id,
        createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: sarah.id,
        orgId: aspca.id,
        type: ActionType.VOLUNTEER,
        comment: "Walked 4 dogs at the shelter today. My heart is full.",
        isPublic: true,
        createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: marcus.id,
        orgId: redcross.id,
        type: ActionType.DONATE,
        amount: 40,
        isPublic: true,
        createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: priya.id,
        orgId: feeding.id,
        type: ActionType.VOLUNTEER,
        comment: "Packed 200 meals at the food bank. Come join next week!",
        isPublic: true,
        createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
      },
    }),
    prisma.action.create({
      data: {
        userId: sarah.id,
        orgId: khan.id,
        type: ActionType.CHEER,
        comment: "Khan Academy is incredible. Everyone should know about this.",
        isPublic: true,
        createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
      },
    }),
  ]);

  console.log(`Created ${actions.length} actions`);

  // Follow relationships
  await Promise.all([
    prisma.follow.upsert({
      where: { followerId_followingId: { followerId: sarah.id, followingId: marcus.id } },
      update: {},
      create: { followerId: sarah.id, followingId: marcus.id },
    }),
    prisma.follow.upsert({
      where: { followerId_followingId: { followerId: sarah.id, followingId: priya.id } },
      update: {},
      create: { followerId: sarah.id, followingId: priya.id },
    }),
    prisma.follow.upsert({
      where: { followerId_followingId: { followerId: marcus.id, followingId: sarah.id } },
      update: {},
      create: { followerId: marcus.id, followingId: sarah.id },
    }),
    prisma.follow.upsert({
      where: { followerId_followingId: { followerId: priya.id, followingId: sarah.id } },
      update: {},
      create: { followerId: priya.id, followingId: sarah.id },
    }),
  ]);

  // Reactions
  await Promise.all([
    prisma.reaction.upsert({
      where: { actionId_userId_type: { actionId: actions[0].id, userId: marcus.id, type: 'CHEER' } },
      update: {},
      create: { actionId: actions[0].id, userId: marcus.id, type: 'CHEER' },
    }),
    prisma.reaction.upsert({
      where: { actionId_userId_type: { actionId: actions[0].id, userId: priya.id, type: 'CHEER' } },
      update: {},
      create: { actionId: actions[0].id, userId: priya.id, type: 'CHEER' },
    }),
    prisma.reaction.upsert({
      where: { actionId_userId_type: { actionId: actions[1].id, userId: sarah.id, type: 'CHEER' } },
      update: {},
      create: { actionId: actions[1].id, userId: sarah.id, type: 'CHEER' },
    }),
    prisma.reaction.upsert({
      where: { actionId_userId_type: { actionId: actions[4].id, userId: priya.id, type: 'CHEER' } },
      update: {},
      create: { actionId: actions[4].id, userId: priya.id, type: 'CHEER' },
    }),
  ]);

  console.log('Seeding complete!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
